sudo apt-get install python3-pyaudio
sudo pip install SpeechRecognition
sudo pip install pyttsx3
sudo pip install pyAudio
sudo pip install pywhatkit
sudo pip install pygame
sudo pip install keyboard
sudo pip install numpy
sudo pip install opencv-contrib-python
sudo pip install wikipedia
sudo pip install cmake
sudo pip install dlib
sudo pip install face_recognition
